import { StyleSheet, Platform } from 'react-native';
import { themeAssets } from '../../theme';
import Fonts from '../../../assets/fonts';

// Platform-specific values
const addCategoryCancelButtonBg = Platform.select({
  android: '#1A1A1A', // Higher contrast for Android 14+
  ios: '#121212',
});
const addCategoryCancelButtonBorderWidth = Platform.select({
  android: 1,
  ios: 0,
});
const addCategoryCancelButtonBorderColor = Platform.select({
  android: '#808080',
  ios: 'transparent',
});

export const getStyles = (theme) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  keyboardView: {
    flex: 1,
  },
  listContent: {
    paddingHorizontal: themeAssets.spacing[5],
    paddingBottom: 120, 
    gap: themeAssets.spacing[3],
  },
  listHeader: {
    gap: themeAssets.spacing[3],
  },
  summaryCard: {
    backgroundColor: theme.colors.elevation.level1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.outline,
  },
  summaryHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: themeAssets.spacing[3],
  },
  summaryTitle: {
    color: theme.colors.text,
  },
  summaryAddButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: theme.colors.secondary,
    backgroundColor: 'transparent',
  },
  summaryAddButtonText: {
    color: theme.colors.secondary,
    fontSize: 14,
    fontFamily: Fonts.semibold,
  },
  summaryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: themeAssets.spacing[4],
  },
  summaryItem: {
    width: '45%',
  },
  summaryLabel: {
    color: theme.colors.onSurfaceVariant,
    fontFamily: Fonts.regular,
  },
  summaryValueIn: {
    color: theme.colors.success,
    fontFamily: Fonts.semibold,
  },
  summaryValueOut: {
    color: theme.colors.error,
    fontFamily: Fonts.semibold,
  },
  summaryValueRemaining: {
    color: theme.colors.text,
    fontFamily: Fonts.semibold,
  },
  summaryGeneric: {
    color: theme.colors.text,
    fontFamily: Fonts.regular,
  },
  comparisonCard: {
    backgroundColor: theme.colors.elevation.level1,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: theme.colors.outline,
  },
  comparisonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: themeAssets.spacing[2],
  },
  comparisonLabel: {
    flex: 1,
    color: theme.colors.text,
  },
  comparisonValues: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: themeAssets.spacing[2],
  },
  comparisonChip: {
    alignSelf: 'flex-start',
  },
  comparisonTitle: {
    color: theme.colors.text,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.elevation.level1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.outline,
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 12,
  },
  searchIcon: {
    marginRight: 0,
  },
  searchInput: {
    flex: 1,
    color: theme.colors.text,
    fontSize: 16,
    padding: 0,
    fontFamily: Fonts.regular,
  },
  filterButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.elevation.level1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.outline,
    paddingVertical: 12,
    paddingHorizontal: 16,
    gap: 8,
  },
  filterButtonText: {
    flex: 1,
    color: theme.colors.text,
    fontSize: 16,
    fontFamily: Fonts.medium,
  },
  expenseItem: {
    backgroundColor: theme.colors.elevation.level1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.outline,
    marginBottom: themeAssets.spacing[2],
  },
  expenseAmounts: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginRight: themeAssets.spacing[3],
  },
  editButton: {
    padding: 6,
    borderRadius: 8,
    backgroundColor: theme.colors.elevation.level1,
    borderWidth: 1,
    borderColor: theme.colors.outline,
    marginLeft: 8,
  },
  deleteButton: {
    padding: 6,
    borderRadius: 8,
    backgroundColor: theme.colors.elevation.level1,
    borderWidth: 1,
    borderColor: theme.colors.error,
    marginLeft: 8,
  },
  expenseAmount: {
    color: theme.colors.text,
    fontSize: 18,
    fontFamily: Fonts.bold,
  },
  moneyIn: {
    color: theme.colors.success,
    fontFamily: Fonts.semibold,
    fontSize: 14,
  },
  moneyOut: {
    color: theme.colors.error,
    fontFamily: Fonts.semibold,
    fontSize: 14,
  },
  expenseNotes: {
    color: theme.colors.onSurfaceVariant,
    fontFamily: Fonts.regular,
  },
  expenseTitle: {
    color: theme.colors.text,
    fontFamily: Fonts.semibold,
  },
  expenseSubtitle: {
    color: theme.colors.onSurfaceVariant,
    fontFamily: Fonts.medium,
  },
  emptyState: {
    alignItems: 'center',
    paddingVertical: themeAssets.spacing[6],
    gap: themeAssets.spacing[2],
  },
  emptyTitle: {
    fontFamily: Fonts.semibold,
    color: theme.colors.text,
  },
  emptySubtitle: {
    textAlign: 'center',
    color: theme.colors.onSurfaceVariant,
    paddingHorizontal: themeAssets.spacing[5],
  },
  emptyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: themeAssets.spacing[2],
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 12,
    backgroundColor: theme.colors.secondary,
    borderWidth: 1,
    borderColor: theme.colors.secondary,
  },
  emptyButtonText: {
    color: theme.colors.onSecondary,
    fontSize: 16,
    fontFamily: Fonts.semibold,
  },
  formActions: {
    flexDirection: 'row',
    gap: themeAssets.spacing[2],
    justifyContent: 'flex-end',
  },
  formButton: {
    flex: 1,
    minWidth: 100,
  },
  errorCard: {
    backgroundColor: theme.colors.elevation.level1,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: theme.colors.error,
  },
  errorTitle: {
    marginBottom: themeAssets.spacing[1],
    color: theme.colors.text,
  },
  errorText: {
    marginBottom: themeAssets.spacing[1],
    color: theme.colors.onSurfaceVariant,
  },
  skeletonBase: {
    borderRadius: 12,
    backgroundColor: theme.colors.elevation.level1,
  },
  skeletonContainer: {
    paddingHorizontal: themeAssets.spacing[5],
    paddingTop: themeAssets.spacing[4],
    paddingBottom: themeAssets.spacing[6],
    gap: themeAssets.spacing[3],
  },
  skeletonTitleShort: {
    width: 120,
    height: 18,
  },
  skeletonButton: {
    width: 72,
    height: 32,
    borderRadius: 16,
  },
  skeletonLabel: {
    width: '60%',
    height: 14,
    marginBottom: themeAssets.spacing[1],
  },
  skeletonLabelWide: {
    flex: 1,
    height: 14,
  },
  skeletonValue: {
    width: '80%',
    height: 22,
  },
  skeletonChipValue: {
    width: 64,
    height: 18,
  },
  skeletonChip: {
    width: 54,
    height: 28,
    borderRadius: 14,
  },
  skeletonNotes: {
    marginTop: themeAssets.spacing[2],
    width: '90%',
    height: 16,
  },
  fabButton: {
    position: 'absolute',
    right: 24,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: theme.colors.secondary,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 8,
    shadowColor: theme.colors.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    zIndex: 1000,
  },
  actionMenuContent: {
    paddingVertical: themeAssets.spacing[2],
    gap: themeAssets.spacing[2],
  },
  actionMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.elevation.level1,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: theme.colors.outline,
    padding: themeAssets.spacing[4],
    gap: themeAssets.spacing[3],
    minHeight: 72,
  },
  actionMenuIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: theme.colors.surface,
    justifyContent: 'center',
    alignItems: 'center',
  },
  actionMenuTextContainer: {
    flex: 1,
    gap: 4,
  },
  actionMenuTitle: {
    color: theme.colors.text,
    fontSize: 16,
    fontFamily: Fonts.semibold,
  },
  actionMenuSubtitle: {
    color: theme.colors.onSurfaceVariant,
    fontSize: 13,
  },
  actionMenuFooter: {
    paddingTop: themeAssets.spacing[2],
  },
  actionMenuButton: {
    minWidth: 100,
  },
  inputWrapper: {
    marginBottom: themeAssets.spacing[3],
  },
  inputLabel: {
    color: theme.colors.onSurfaceVariant,
    fontSize: 14,
    fontFamily: Fonts.semibold,
    marginBottom: themeAssets.spacing[1],
  },
  monthPickerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: theme.colors.elevation.level1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.outline,
    paddingVertical: 14,
    paddingHorizontal: 16,
    minHeight: 48,
  },
  monthPickerText: {
    color: theme.colors.text,
    fontSize: 16,
    flex: 1,
  },
  monthPickerPlaceholder: {
    color: theme.colors.onSurfaceVariant,
  },
  monthPickerModal: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  monthPickerBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  monthPickerContainer: {
    backgroundColor: theme.colors.elevation.level1,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '70%',
    borderWidth: 1,
    borderColor: theme.colors.outline,
  },
  monthPickerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.outline,
  },
  monthPickerTitle: {
    color: theme.colors.text,
    fontSize: 18,
    fontFamily: Fonts.semibold,
  },
  monthPickerCloseButton: {
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  monthPickerCloseText: {
    color: theme.colors.secondary,
    fontSize: 16,
    fontFamily: Fonts.semibold,
  },
  monthPickerList: {
    paddingVertical: 8,
  },
  monthPickerItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.outline,
  },
  monthPickerItemSelected: {
    backgroundColor: theme.colors.surface,
  },
  monthPickerItemText: {
    color: theme.colors.text,
    fontSize: 16,
  },
  monthPickerItemTextSelected: {
    color: theme.colors.secondary,
    fontFamily: Fonts.semibold,
  },
  monthPickerCheckmark: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: theme.colors.secondary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  monthPickerCheckmarkText: {
    color: theme.colors.onSecondary,
    fontSize: 14,
    fontFamily: Fonts.bold,
  },
  addCategoryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.outline,
  },
  addCategoryButtonText: {
    color: theme.colors.secondary,
    fontSize: 16,
    fontFamily: Fonts.semibold,
  },
  addCategoryContainer: {
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.outline,
    gap: 12,
  },
  addCategoryInput: {
    backgroundColor: theme.colors.surface,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.outline,
    paddingVertical: 12,
    paddingHorizontal: 16,
    color: theme.colors.text,
    fontSize: 16,
  },
  addCategoryActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 12,
    alignItems: 'center',
  },
  addCategoryCancelButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: theme.colors.elevation.level1,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.colors.outline,
  },
  addCategorySaveButton: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 20,
    backgroundColor: theme.colors.secondary,
  },
  addCategorySaveButtonDisabled: {
    opacity: 0.5,
  },
  addCategorySaveText: {
    color: theme.colors.onSecondary,
    fontSize: 14,
    fontFamily: Fonts.semibold,
  },
  filterSheetContent: {
    paddingVertical: themeAssets.spacing[2],
    gap: themeAssets.spacing[1],
  },
  filterSheetScrollContent: {
    paddingBottom: themeAssets.spacing[4],
  },
  filterSection: {
    marginBottom: themeAssets.spacing[4],
  },
  filterSectionTitle: {
    color: theme.colors.onSurfaceVariant,
    fontSize: 14,
    fontFamily: Fonts.semibold,
    marginBottom: themeAssets.spacing[2],
    paddingHorizontal: themeAssets.spacing[1],
  },
  filterSheetItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 12,
    backgroundColor: theme.colors.elevation.level1,
    borderWidth: 1,
    borderColor: theme.colors.outline,
    marginBottom: themeAssets.spacing[2],
  },
  filterSheetItemSelected: {
    backgroundColor: theme.colors.surface,
    borderColor: theme.colors.secondary,
  },
  filterSheetItemText: {
    color: theme.colors.text,
    fontSize: 16,
  },
  filterSheetItemTextSelected: {
    color: theme.colors.secondary,
    fontFamily: Fonts.semibold,
  },
  filterSheetCheckmark: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: theme.colors.secondary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  filterSheetCheckmarkText: {
    color: theme.colors.onSecondary,
    fontSize: 14,
    fontFamily: Fonts.bold,
  },
  loadMoreContainer: {
    paddingVertical: themeAssets.spacing[4],
    alignItems: 'center',
  },
  loadMoreText: {
    color: theme.colors.onSurfaceVariant,
    fontSize: 14,
  },
  dateHeader: {
    paddingVertical: 12,
    paddingHorizontal: 4,
    backgroundColor: 'transparent',
    marginTop: themeAssets.spacing[2],
  },
  dateHeaderText: {
    color: theme.colors.onSurfaceVariant,
    fontSize: 13,
    fontFamily: Fonts.semibold,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  deleteContent: {
    paddingVertical: themeAssets.spacing[2],
    gap: themeAssets.spacing[4],
  },
  deleteHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: themeAssets.spacing[3],
    marginBottom: themeAssets.spacing[1],
  },
  deleteIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  deleteTitle: {
    fontSize: 20,
    color: theme.colors.error,
    fontFamily: Fonts.bold,
  },
  deleteMessage: {
    color: theme.colors.text,
    fontSize: 16,
    fontFamily: Fonts.regular,
    lineHeight: 24,
  },
  deleteDetails: {
    backgroundColor: theme.colors.elevation.level1,
    borderRadius: 12,
    padding: themeAssets.spacing[4],
    borderWidth: 1,
    borderColor: theme.colors.outline,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  deleteAmount: {
    fontSize: 24,
    color: theme.colors.text,
    fontFamily: Fonts.bold,
  },
  deleteCategoryChip: {
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.outline,
  },
  deleteCategoryText: {
    color: theme.colors.onSurfaceVariant,
  },
  deleteWarning: {
    color: theme.colors.error,
    fontSize: 14,
    fontFamily: Fonts.medium,
    textAlign: 'center',
  },
  deleteActions: {
    flexDirection: 'row',
    gap: themeAssets.spacing[3],
    marginTop: themeAssets.spacing[2],
  },
  deleteCancelButton: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.outline,
  },
  typeFilterItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: theme.colors.elevation.level1,
    borderWidth: 1,
    borderColor: theme.colors.outline,
  },
  deleteConfirmButton: {
    flex: 1,
    borderRadius: 12,
  },
});
